const state = {
 role:'director', page:'dashboard', selectedChild:1, selectedGroup:1, selectedLesson:1,
 children:[
  {id:1,name:'Агафонов Евгений',birth:'2015-04-12',school:'СОШ № 1',grade:'5А',shift:'1',parent:'Агафонова Марина',phone:'+7 914 555-18-04',status:'Активный',note:'Любит конструирование, быстро работает в паре.',enrollments:[{direction:'Робототехника',groupId:1,individualPrice:null,balance:1},{direction:'Программирование',groupId:3,individualPrice:null,balance:3}]},
  {id:2,name:'Петров Максим',birth:'2016-09-03',school:'Гимназия № 2',grade:'4Б',shift:'1',parent:'Петрова Ольга',phone:'+7 924 210-44-31',status:'Активный',note:'',enrollments:[{direction:'Робототехника',groupId:1,individualPrice:null,balance:0}]},
  {id:3,name:'Сидоров Артём',birth:'2015-11-21',school:'СОШ № 6',grade:'5В',shift:'2',parent:'Сидорова Анна',phone:'+7 914 781-33-20',status:'Активный',note:'Иногда приходит на соседнюю группу.',enrollments:[{direction:'Робототехника',groupId:1,individualPrice:null,balance:-1}]},
  {id:4,name:'Козлов Максим',birth:'2014-02-17',school:'Лицей',grade:'6А',shift:'1',parent:'Козлова Ирина',phone:'+7 962 100-77-55',status:'Активный',note:'',enrollments:[{direction:'Робототехника',groupId:2,individualPrice:null,balance:4}]},
  {id:5,name:'Иванов Алексей',birth:'2015-06-08',school:'СОШ № 3',grade:'5Б',shift:'2',parent:'Иванова Светлана',phone:'+7 914 610-20-28',status:'Пауза',note:'Пауза до октября.',enrollments:[{direction:'Робототехника',groupId:2,individualPrice:null,balance:2}]},
  {id:6,name:'Волкова София',birth:'2017-01-19',school:'СОШ № 1',grade:'3А',shift:'1',parent:'Волкова Екатерина',phone:'+7 914 443-19-91',status:'Лид',note:'Была на пробном.',enrollments:[{direction:'Робототехника',groupId:4,individualPrice:null,balance:0}]}
 ],
 groups:[
  {id:1,name:'Роботы · Чт 14:00',direction:'Робототехника',siteId:1,teacherId:1,day:'Четверг',time:'14:00–15:30',project:'iCubeRobots',price:null,active:true},
  {id:2,name:'Роботы · Сб 10:00',direction:'Робототехника',siteId:2,teacherId:2,day:'Суббота',time:'10:00–11:30',project:'iCubeRobots',price:950,active:true},
  {id:3,name:'Scratch · Пт 16:00',direction:'Программирование',siteId:1,teacherId:1,day:'Пятница',time:'16:00–17:30',project:'iCubeRobots',price:null,active:true},
  {id:4,name:'Зебра · Роботы 18:00',direction:'Робототехника',siteId:3,teacherId:2,day:'Среда',time:'18:00–19:30',project:'Зебра',price:null,active:true}
 ],
 sites:[
  {id:1,name:'Школа № 1',type:'Школа',address:'ул. Школьная, 12',note:'Кабинет технологии, 2 этаж'},
  {id:2,name:'ДК «Океан»',type:'ДК',address:'ул. Советская, 18',note:'Малый зал'},
  {id:3,name:'Развивающий центр «Зебра»',type:'Развивающий центр',address:'ул. Молодёжная, 7',note:'Вход со двора'}
 ],
 teachers:[
  {id:1,name:'Иванов Сергей',phone:'+7 914 500-12-11',active:true,directions:['Робототехника','Программирование']},
  {id:2,name:'Смирнова Алина',phone:'+7 924 330-52-70',active:true,directions:['Робототехника']},
  {id:3,name:'Ким Андрей',phone:'+7 914 200-01-09',active:false,directions:['Программирование']}
 ],
 lessons:[
  {id:1,date:'09.09.2026',time:'14:00–15:30',groupId:1,teacherId:1,status:'Запланировано',topic:'',attendance:{1:true,2:true,3:false},extras:[],photos:{},started:false,done:false,intro:false,emptyTrip:false,attendanceApplied:false,summary:null},
  {id:2,date:'09.09.2026',time:'18:00–19:30',groupId:4,teacherId:2,status:'Запланировано',topic:'',attendance:{6:true},extras:[],photos:{},started:false,done:false,intro:false,emptyTrip:false,attendanceApplied:false,summary:null},
  {id:3,date:'10.09.2026',time:'14:00–15:30',groupId:1,teacherId:1,status:'Запланировано',topic:'',attendance:{1:false,2:false,3:false},extras:[],photos:{},started:false,done:false,intro:false,emptyTrip:false,attendanceApplied:false,summary:null},
  {id:4,date:'05.09.2026',time:'10:00–11:30',groupId:2,teacherId:2,status:'Проведено',topic:'Редукторы и передаточное отношение',attendance:{4:true,5:true},extras:[{childId:3,trial:false}],photos:{4:true,5:true,3:true},started:true,done:true,intro:false,emptyTrip:false,attendanceApplied:false,summary:null}
 ],
 payments:[
  {id:1,date:'01.09.2026',childId:1,direction:'Робототехника',amount:4100,method:'На счёт iCube',price:1025,lessons:4},
  {id:2,date:'02.09.2026',childId:2,direction:'Робототехника',amount:4100,method:'На счёт iCube',price:1025,lessons:4},
  {id:3,date:'03.09.2026',childId:4,direction:'Робототехника',amount:3800,method:'На счёт iCube',price:950,lessons:4},
  {id:4,date:'04.09.2026',childId:6,direction:'Робототехника',amount:4100,method:'Наличными партнёру',price:1025,lessons:4}
 ],
 refunds:[{id:1,date:'28.08.2026',childId:5,direction:'Робототехника',amount:1025,price:1025,lessons:1}],
 settings:{robotPrice:1025,codePrice:900,salaryFix:600,salaryChild:100,salaryIntro:600,salaryEmpty:300,tax:4,icubeShare:40,partnerShare:60},
 modal:null
};
const byId=(arr,id)=>arr.find(x=>x.id===Number(id));
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0))+' ₽';
const initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('');
const statusBadge=s=>({Активный:'green',Лид:'blue',Пауза:'amber',Закончил:'gray'}[s]||'gray');
const groupChildren=id=>state.children.filter(c=>c.enrollments.some(e=>e.groupId===id));
const effectivePrice=e=>e?.individualPrice ?? (byId(state.groups,e?.groupId)?.price ?? (e?.direction==='Программирование'?state.settings.codePrice:state.settings.robotPrice));
function navTo(p){state.page=p;render();window.scrollTo({top:0,behavior:'smooth'})}
function openChild(id){state.selectedChild=id;state.page='child';render()}
function openGroup(id){state.selectedGroup=id;state.page='group';render()}
function openLesson(id,teacher=false){state.selectedLesson=id;state.page=teacher?'teacherLesson':'lesson';render()}
function modal(html){state.modal=html;render()}
function closeModal(){state.modal=null;render()}
const navItems=[
 ['dashboard','Главная'],['children','Дети'],['groups','Группы'],['calendar','Календарь'],['payments','Оплаты'],['refunds','Возвраты'],['balances','Балансы / долги'],['teachers','Преподаватели'],['sites','Площадки'],['salary','Зарплата'],['partner','Партнёр'],['stats','Статистика'],['settings','Настройки']
];
function shell(content,title='iCube CRM'){
 return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">iC</div><div>iCube CRM</div></div><div class="nav">${navItems.map(([p,l],i)=>`${i===7?'<small>Управление</small>':''}<button class="${state.page===p?'active':''}" onclick="navTo('${p}')">${l}</button>`).join('')}</div></aside><main class="main"><header class="topbar"><div class="crumb">${title}</div><div class="top-actions"><div><select class="role-switch" onchange="state.role=this.value; state.page=this.value==='teacher'?'teacherToday':'dashboard'; render()"><option value="director" ${state.role==='director'?'selected':''}>Директор</option><option value="teacher" ${state.role==='teacher'?'selected':''}>Преподаватель</option></select><div class="muted mini">Режим прототипа</div></div><div class="avatar">ИЯ</div></div></header><div class="content">${content}</div><div class="mobile-nav">${[['dashboard','Главная'],['children','Дети'],['calendar','Календарь'],['payments','Оплаты'],['settings','Ещё']].map(([p,l])=>`<button class="${state.page===p?'active':''}" onclick="navTo('${p}')">${l}</button>`).join('')}</div></main></div>`;
}
function pageHead(title,sub='',action=''){return `<div class="page-head"><div><h1>${title}</h1><div class="muted">${sub}</div></div>${action}</div>`}
function dashboard(){
 const active=state.children.filter(x=>x.status==='Активный').length, leads=state.children.filter(x=>x.status==='Лид').length;
 const low=state.children.filter(c=>c.enrollments.some(e=>e.balance===1)).length, zero=state.children.filter(c=>c.enrollments.some(e=>e.balance===0)).length, debt=state.children.filter(c=>c.enrollments.some(e=>e.balance<0)).length;
 const revenue=state.payments.reduce((a,b)=>a+b.amount,0);
 return pageHead('Главная','Среда, 9 сентября · обзор клуба')+`
 <div class="grid cols-4"><div class="card metric"><div class="label">Активные дети</div><div class="value">${active}</div><div class="sub">+2 за последние 30 дней</div></div><div class="card metric"><div class="label">Лиды</div><div class="value">${leads}</div><div class="sub">1 был на пробном</div></div><div class="card metric"><div class="label">Активные группы</div><div class="value">${state.groups.filter(g=>g.active).length}</div><div class="sub">2 направления</div></div><div class="card metric"><div class="label">Оплаты в сентябре</div><div class="value">${money(revenue)}</div><div class="sub">тестовые данные</div></div></div>
 <div class="grid cols-2" style="margin-top:16px"><div class="card pad"><div class="section-title"><h2>Требует внимания</h2><span class="muted mini">по балансам направлений</span></div><div class="attention"><button class="warn" onclick="navTo('balances')"><span>Осталось 1 занятие</span><b>${low}</b></button><button class="zero" onclick="navTo('balances')"><span>Осталось 0</span><b>${zero}</b></button><button class="debt" onclick="navTo('balances')"><span>Должники</span><b>${debt}</b></button></div></div>
 <div class="card pad"><div class="section-title"><h2>Ближайшие занятия</h2><button class="btn" onclick="navTo('calendar')">Календарь</button></div><div class="list">${state.lessons.filter(l=>!l.done).slice(0,3).map(l=>{let g=byId(state.groups,l.groupId);return `<div class="kpi-line clickable" onclick="openLesson(${l.id})"><div><b>${l.time.split('–')[0]} · ${g.direction}</b><div class="muted mini">${g.name} · ${byId(state.sites,g.siteId).name}</div></div><span class="badge ${g.project==='Зебра'?'purple':'blue'}">${g.project}</span></div>`}).join('')}</div></div></div>
 <div class="card pad" style="margin-top:16px"><div class="section-title"><h2>Сегодня</h2><span class="muted">2 занятия</span></div><div class="grid cols-2">${state.lessons.filter(l=>l.date==='09.09.2026').map(l=>{let g=byId(state.groups,l.groupId);return `<div style="border:1px solid var(--line);border-radius:12px;padding:14px"><div class="muted mini">${l.time}</div><b style="font-size:16px">${g.name}</b><div class="muted">${byId(state.sites,g.siteId).name} · ${byId(state.teachers,l.teacherId).name}</div><button class="btn soft" style="margin-top:12px" onclick="openLesson(${l.id})">Открыть занятие</button></div>`}).join('')}</div></div>`;
}
function children(){
 let rows=state.children.map(c=>`<div class="row clickable" onclick="openChild(${c.id})"><div><b>${c.name}</b><div class="muted mini">${c.school} · ${c.grade}</div></div><div><span class="badge ${statusBadge(c.status)}">${c.status}</span></div><div>${c.enrollments.map(e=>`<div class="mini">${e.direction}</div>`).join('')}</div><div>${c.enrollments.map(e=>`<span class="money ${e.balance<0?'negative':e.balance===0?'':'positive'}">${e.balance}</span>`).join(' / ')}</div><div>›</div></div>`).join('');
 return pageHead('Дети','Один ребёнок — одна карточка, направления и балансы хранятся отдельно','<button class="btn primary" onclick="childForm()">+ Добавить ребёнка</button>')+`<div class="toolbar"><input class="input search" placeholder="Поиск по имени или родителю" oninput="filterRows(this.value)"><select class="select" style="max-width:180px"><option>Все статусы</option><option>Активный</option><option>Лид</option><option>Пауза</option></select></div><div class="card list" id="childRows"><div class="row header"><div>Ребёнок</div><div>Статус</div><div>Направления</div><div>Баланс</div><div></div></div>${rows}</div>`;
}
function filterRows(q){document.querySelectorAll('#childRows .row.clickable').forEach(el=>el.style.display=el.innerText.toLowerCase().includes(q.toLowerCase())?'grid':'none')}
function childForm(id=null){
 const c=id?byId(state.children,id):null;
 modal(`<h3>${c?'Редактировать ребёнка':'Новый ребёнок'}</h3><div class="form-grid"><div class="field span-2"><label>ФИО</label><input class="input" id="cf-name" value="${c?.name||''}" placeholder="Фамилия Имя"></div><div class="field"><label>Дата рождения</label><input class="input" id="cf-birth" type="date" value="${c?.birth||''}"></div><div class="field"><label>Статус</label><select class="select" id="cf-status">${['Лид','Активный','Пауза','Закончил'].map(s=>`<option ${c?.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Школа</label><input class="input" id="cf-school" value="${c?.school||''}"></div><div class="field"><label>Класс</label><input class="input" id="cf-grade" value="${c?.grade||''}"></div><div class="field"><label>Родитель</label><input class="input" id="cf-parent" value="${c?.parent||''}"></div><div class="field"><label>Телефон</label><input class="input" id="cf-phone" value="${c?.phone||''}"></div><div class="field span-2"><label>Основная группа</label><select class="select" id="cf-group">${state.groups.map(g=>`<option value="${g.id}" ${c?.enrollments?.[0]?.groupId===g.id?'selected':''}>${g.name}</option>`).join('')}<option value="new">+ Создать группу</option></select><div class="muted mini" style="margin-top:5px">В production это будет searchable select с быстрым созданием связанной сущности.</div></div><div class="field span-2"><label>Примечание</label><textarea class="textarea" id="cf-note">${c?.note||''}</textarea></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Отмена</button><button class="btn primary" onclick="saveChild(${c?.id||'null'})">Сохранить</button></div>`);
}
function saveChild(id){
 const name=document.querySelector('#cf-name').value.trim()||'Новый ребёнок', groupId=Number(document.querySelector('#cf-group').value)||1;
 if(id){let c=byId(state.children,id);Object.assign(c,{name,birth:document.querySelector('#cf-birth').value,school:document.querySelector('#cf-school').value,grade:document.querySelector('#cf-grade').value,parent:document.querySelector('#cf-parent').value,phone:document.querySelector('#cf-phone').value,status:document.querySelector('#cf-status').value,note:document.querySelector('#cf-note').value});let g=byId(state.groups,groupId);let e=c.enrollments.find(x=>x.direction===g.direction);if(e)e.groupId=groupId;}
 else{let nid=Math.max(...state.children.map(x=>x.id))+1;state.children.push({id:nid,name,birth:document.querySelector('#cf-birth').value,school:document.querySelector('#cf-school').value,grade:document.querySelector('#cf-grade').value,shift:'1',parent:document.querySelector('#cf-parent').value,phone:document.querySelector('#cf-phone').value,status:document.querySelector('#cf-status').value,note:document.querySelector('#cf-note').value,enrollments:[{direction:byId(state.groups,groupId).direction,groupId,individualPrice:null,balance:0}]});state.selectedChild=nid;}
 state.modal=null;state.page='child';render();
}
function child(){
 const c=byId(state.children,state.selectedChild); if(!c)return children();
 return '<button class="btn" style="margin-bottom:14px" onclick="navTo(\'children\')">← Дети</button>'+pageHead(c.name,`${c.school} · ${c.grade} · ${c.parent}`,`<button class="btn" onclick="childForm(${c.id})">Редактировать</button>`)+`
 <div class="tabs"><button class="active">Обзор</button><button>Оплаты</button><button>Посещения</button><button>Возвраты</button></div><div class="split"><div class="card pad"><div class="section-title"><h2>Направления</h2><span class="badge ${statusBadge(c.status)}">${c.status}</span></div>${c.enrollments.map(e=>{let g=byId(state.groups,e.groupId);return `<div style="border-top:1px solid var(--line);padding:14px 0"><div style="display:flex;justify-content:space-between;gap:12px"><div><b>${e.direction}</b><div class="muted">${g?.name||'Без группы'}</div></div><div style="text-align:right"><div class="money ${e.balance<0?'negative':e.balance>0?'positive':''}">${e.balance} занятий</div><div class="muted mini">${money(effectivePrice(e))} / занятие</div></div></div><button class="btn soft" style="margin-top:10px" onclick="paymentForm(${c.id},'${e.direction}')">+ Оплата</button></div>`}).join('')}</div>
 <div class="card pad"><div class="section-title"><h2>Контакты и данные</h2></div><div class="info-list"><div class="info-line"><span>Дата рождения</span><b>${c.birth}</b></div><div class="info-line"><span>Смена</span><b>${c.shift}</b></div><div class="info-line"><span>Родитель</span><b>${c.parent}</b></div><div class="info-line"><span>Телефон</span><b>${c.phone}</b></div><div class="info-line"><span>Примечание</span><span style="text-align:right">${c.note||'—'}</span></div></div></div></div>
 <div class="grid cols-2" style="margin-top:16px"><div class="card pad"><div class="section-title"><h2>Последние оплаты</h2><button class="btn" onclick="navTo('payments')">Все</button></div>${state.payments.filter(p=>p.childId===c.id).map(p=>`<div class="kpi-line"><div><b>${p.direction}</b><div class="muted mini">${p.date} · ${p.method}</div></div><div class="money positive">+${p.lessons} · ${money(p.amount)}</div></div>`).join('')||'<div class="empty">Оплат пока нет</div>'}</div><div class="card pad"><div class="section-title"><h2>История посещений</h2></div><div class="kpi-line"><div><b>05.09 · Робототехника</b><div class="muted mini">Редукторы и передаточное отношение</div></div><span class="badge green">Был</span></div><div class="kpi-line"><div><b>29.08 · Робототехника</b><div class="muted mini">Зубчатые передачи</div></div><span class="badge green">Был</span></div></div></div>`;
}
function groups(){
 return pageHead('Группы','Регулярное расписание, площадка, преподаватель, проект и цена','<button class="btn primary" onclick="groupForm()">+ Новая группа</button>')+`<div class="grid cols-3">${state.groups.map(g=>`<div class="card pad clickable" onclick="openGroup(${g.id})"><div style="display:flex;justify-content:space-between;gap:8px"><span class="badge ${g.project==='Зебра'?'purple':'blue'}">${g.project}</span><span class="badge ${g.active?'green':'gray'}">${g.active?'Активна':'Неактивна'}</span></div><h3 style="margin:14px 0 5px">${g.name}</h3><div class="muted">${g.direction}</div><div class="info-list" style="margin-top:12px"><div class="info-line"><span>Когда</span><b>${g.day}, ${g.time}</b></div><div class="info-line"><span>Площадка</span><b>${byId(state.sites,g.siteId).name}</b></div><div class="info-line"><span>Преподаватель</span><b>${byId(state.teachers,g.teacherId).name}</b></div><div class="info-line"><span>Детей</span><b>${groupChildren(g.id).length}</b></div><div class="info-line"><span>Цена</span><b>${g.price?money(g.price):'Наследуется'}</b></div></div></div>`).join('')}</div>`;
}
function groupForm(){modal(`<h3>Новая группа</h3><div class="form-grid"><div class="field span-2"><label>Название</label><input class="input" id="gf-name" value="Новая группа"></div><div class="field"><label>Направление</label><select class="select" id="gf-dir"><option>Робототехника</option><option>Программирование</option></select></div><div class="field"><label>Проект</label><select class="select" id="gf-project"><option>iCubeRobots</option><option>Зебра</option></select></div><div class="field"><label>Площадка</label><select class="select" id="gf-site">${state.sites.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></div><div class="field"><label>Преподаватель</label><select class="select" id="gf-teacher">${state.teachers.filter(t=>t.active).map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="field"><label>День</label><select class="select" id="gf-day"><option>Понедельник</option><option>Вторник</option><option>Среда</option><option>Четверг</option><option>Пятница</option><option>Суббота</option></select></div><div class="field"><label>Время</label><input class="input" id="gf-time" value="15:00–16:30"></div><div class="field span-2"><label>Специальная цена, ₽ (необязательно)</label><input class="input" id="gf-price" type="number" placeholder="Пусто = цена направления"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Отмена</button><button class="btn primary" onclick="saveGroup()">Создать</button></div>`)}
function saveGroup(){let id=Math.max(...state.groups.map(x=>x.id))+1;state.groups.push({id,name:document.querySelector('#gf-name').value,direction:document.querySelector('#gf-dir').value,siteId:Number(document.querySelector('#gf-site').value),teacherId:Number(document.querySelector('#gf-teacher').value),day:document.querySelector('#gf-day').value,time:document.querySelector('#gf-time').value,project:document.querySelector('#gf-project').value,price:Number(document.querySelector('#gf-price').value)||null,active:true});state.selectedGroup=id;state.modal=null;state.page='group';render()}
function group(){
 const g=byId(state.groups,state.selectedGroup), kids=groupChildren(g.id);
 return '<button class="btn" style="margin-bottom:14px" onclick="navTo(\'groups\')">← Группы</button>'+pageHead(g.name,`${g.direction} · ${g.project}`,'<button class="btn">Редактировать</button>')+`<div class="split"><div class="card pad"><div class="section-title"><h2>Основные данные</h2><span class="badge green">Активна</span></div><div class="info-line"><span>Регулярное расписание</span><b>${g.day}, ${g.time}</b></div><div class="info-line"><span>Площадка</span><b>${byId(state.sites,g.siteId).name}</b></div><div class="info-line"><span>Основной преподаватель</span><b>${byId(state.teachers,g.teacherId).name}</b></div><div class="info-line"><span>Цена группы</span><b>${g.price?money(g.price):'Наследуется от направления'}</b></div><div class="notice" style="margin-top:12px">Изменение конкретного занятия в календаре не меняет регулярное расписание группы.</div></div><div class="card pad"><div class="section-title"><h2>Основная группа</h2><b>${kids.length} детей</b></div>${kids.map(c=>`<div class="kpi-line clickable" onclick="openChild(${c.id})"><div><b>${c.name}</b><div class="muted mini">${c.parent}</div></div><span class="badge ${statusBadge(c.status)}">${c.status}</span></div>`).join('')||'<div class="empty">Нет детей</div>'}</div></div>`;
}
function sites(){return pageHead('Площадки','Места проведения занятий','<button class="btn primary" onclick="simpleAdd(\'site\')">+ Площадка</button>')+`<div class="grid cols-3">${state.sites.map(s=>`<div class="card pad"><span class="badge gray">${s.type}</span><h3>${s.name}</h3><div class="muted">${s.address}</div><div style="margin-top:13px">${s.note}</div><div class="muted mini" style="margin-top:12px">${state.groups.filter(g=>g.siteId===s.id).length} групп</div></div>`).join('')}</div>`}
function teachers(){return pageHead('Преподаватели','Контакты, направления и активность','<button class="btn primary" onclick="simpleAdd(\'teacher\')">+ Преподаватель</button>')+`<div class="card list"><div class="row header"><div>Преподаватель</div><div>Телефон</div><div>Направления</div><div>Статус</div><div></div></div>${state.teachers.map(t=>`<div class="row"><div><b>${t.name}</b></div><div>${t.phone}</div><div>${t.directions.join(', ')}</div><div><span class="badge ${t.active?'green':'gray'}">${t.active?'Активен':'Неактивен'}</span></div><div>•••</div></div>`).join('')}</div>`}
function simpleAdd(type){modal(`<h3>${type==='site'?'Новая площадка':'Новый преподаватель'}</h3><div class="notice">В v1 показан UX быстрого создания. Полная форма появится после проверки структуры интерфейса.</div><div class="field" style="margin-top:14px"><label>Название / ФИО</label><input class="input" id="simple-name"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Отмена</button><button class="btn primary" onclick="closeModal()">Сохранить</button></div>`)}
function calendar(){
 const days=['07.09','08.09','09.09','10.09','11.09','12.09','13.09'];return pageHead('Календарь','Конкретные занятия создаются из регулярного расписания, но могут меняться отдельно','<button class="btn">Сегодня</button>')+`<div class="toolbar"><button class="btn soft">Неделя</button><button class="btn">Месяц</button><select class="select" style="max-width:220px"><option>Все проекты</option><option>iCubeRobots</option><option>Зебра</option></select></div><div class="calendar">${days.map(d=>`<div class="day"><div class="date">${d}${d==='09.09'?' · сегодня':''}</div>${state.lessons.filter(l=>l.date.startsWith(d)).map(l=>{let g=byId(state.groups,l.groupId);return `<div class="event ${g.project==='Зебра'?'partner':''} ${l.done?'done':''}" onclick="openLesson(${l.id})"><b>${l.time.split('–')[0]}</b> ${g.direction}<div>${g.name}</div></div>`}).join('')}</div>`).join('')}</div>`;
}
function lesson(){
 const l=byId(state.lessons,state.selectedLesson),g=byId(state.groups,l.groupId),t=byId(state.teachers,l.teacherId),kids=groupChildren(g.id);
 return '<button class="btn" style="margin-bottom:14px" onclick="navTo(\'calendar\')">← Календарь</button>'+pageHead(`${l.date} · ${g.direction}`,`${l.time} · ${byId(state.sites,g.siteId).name}`,'<button class="btn">Изменить занятие</button>')+`<div class="split"><div class="card pad"><div class="section-title"><h2>Занятие</h2><div class="lesson-status"><span class="badge ${l.done?'green':'blue'}">${l.done?'Проведено':'Запланировано'}</span><span class="badge ${g.project==='Зебра'?'purple':'gray'}">${g.project}</span></div></div><div class="info-line"><span>Группа</span><b>${g.name}</b></div><div class="info-line"><span>Фактический преподаватель</span><b>${t.name}</b></div><div class="info-line"><span>Тема</span><b>${l.topic||'Не указана'}</b></div><div class="info-line"><span>Присутствовало</span><b>${Object.values(l.attendance).filter(Boolean).length+l.extras.length}</b></div><div class="notice" style="margin-top:14px">Директор может задним числом изменить финансовый статус занятия, не меняя посещения и фотографии.</div><div style="display:grid;gap:9px;margin-top:14px"><label class="student-check"><input type="checkbox" ${l.intro?'checked':''} onchange="lToggle('intro',this.checked)"><span><b>Ознакомительное занятие всей группы</b><div class="muted mini">Фиксированная ставка ЗП; преподаватель эту настройку не видит.</div></span></label><label class="student-check"><input type="checkbox" ${l.emptyTrip?'checked':''} onchange="lToggle('emptyTrip',this.checked)"><span><b>Пустой выезд</b><div class="muted mini">Не ставится автоматически при нулевой посещаемости.</div></span></label></div></div><div class="card pad"><div class="section-title"><h2>Посещаемость</h2><button class="btn soft" onclick="state.role='teacher';openLesson(${l.id},true)">Открыть как преподаватель</button></div>${kids.map(c=>`<div class="kpi-line"><b>${c.name}</b><span class="badge ${l.attendance[c.id]?'green':'gray'}">${l.attendance[c.id]?'Был':'Не отмечен'}</span></div>`).join('')}${l.extras.map(e=>`<div class="kpi-line"><div><b>${byId(state.children,e.childId).name}</b><div class="muted mini">Из другой группы</div></div><span class="badge green">Был</span></div>`).join('')}</div></div>`;
}
function lToggle(k,v){byId(state.lessons,state.selectedLesson)[k]=v;render()}
function teacherShell(content){return `<div class="teacher-shell"><div class="teacher-top"><div class="teacher-top-inner"><div><div class="mini" style="color:#98a2b3">iCube CRM · преподаватель</div><b>Иванов Сергей</b></div><div><select class="role-switch" onchange="state.role=this.value;state.page=this.value==='director'?'dashboard':'teacherToday';render()"><option value="teacher">Преподаватель</option><option value="director">Директор</option></select><div class="mini" style="color:#98a2b3">Режим прототипа</div></div></div></div><div class="teacher-content">${content}</div></div>`}
function teacherToday(){
 const ls=state.lessons.filter(l=>l.date==='09.09.2026'&&l.teacherId===1);return `<h1 style="margin:2px 0 4px">Сегодня</h1><div class="muted" style="margin-bottom:18px">Среда, 9 сентября</div>${ls.map(l=>{let g=byId(state.groups,l.groupId);return `<div class="teacher-card" onclick="openLesson(${l.id},true)"><div class="teacher-lesson-head"><div><div class="teacher-time">${l.time.split('–')[0]}</div><h3 style="margin:4px 0">${g.direction}</h3><div class="muted">${g.name}<br>${byId(state.sites,g.siteId).name}</div></div><span class="badge ${l.started?'green':'blue'}">${l.done?'Завершено':l.started?'Идёт':'Скоро'}</span></div><button class="btn primary" style="width:100%;margin-top:14px">Открыть занятие</button></div>`}).join('')}`;
}
function teacherLesson(){
 const l=byId(state.lessons,state.selectedLesson),g=byId(state.groups,l.groupId),kids=groupChildren(g.id);
 return `<button class="btn" onclick="state.page='teacherToday';render()">← Сегодня</button><div style="margin:16px 0"><div class="muted">${l.date} · ${l.time}</div><h1 style="margin:4px 0">${g.direction}</h1><div class="muted">${g.name} · ${byId(state.sites,g.siteId).name}</div></div>
 ${!l.started?`<div class="teacher-card"><h3 style="margin-top:0">Занятие готово</h3><p class="muted">После начала можно отмечать присутствующих, тему и фотографии.</p><button class="btn primary big-action" style="width:100%" onclick="startLesson()">Начать занятие</button></div>`:`
 <div class="teacher-card"><div class="section-title"><h2>Основная группа</h2><span class="badge blue">${kids.length} детей</span></div><div class="attendance">${kids.map(c=>studentCheck(c,l,false)).join('')}</div></div>
 <div class="teacher-card"><div class="section-title"><h2>Добавлены на занятие</h2></div>${l.extras.map(e=>studentCheck(byId(state.children,e.childId),l,true,e)).join('')||'<div class="muted mini">Пока никого</div>'}<div style="margin-top:12px"><input class="input" id="extraSearch" placeholder="Начните вводить фамилию…" oninput="showExtraResults(this.value)"><div id="extraResults"></div></div></div>
 <div class="teacher-card"><label class="field"><label>Тема занятия</label><textarea class="textarea" placeholder="Например: Датчик расстояния" oninput="byId(state.lessons,state.selectedLesson).topic=this.value">${l.topic}</textarea></label></div>
 <div class="teacher-sticky">${l.done?'<div class="teacher-card" style="background:var(--greenbg)"><b style="font-size:18px;color:var(--green)">Занятие завершено ✓</b><div class="muted" style="margin-top:8px">Баланс посещений применён один раз. Пробные посещения не списаны.</div></div>':'<button class="btn primary big-action" onclick="finishLesson()">Завершить занятие</button>'}</div>`}`;
}
function studentCheck(c,l,extra,e){
 const present=extra?true:!!l.attendance[c.id], photo=!!l.photos[c.id];
 return `<div class="student-check">${extra?'<span>✓</span>':`<input type="checkbox" ${present?'checked':''} onchange="attend(${c.id},this.checked)">`}<div><b>${c.name}</b>${extra?'<div class="muted mini">из другой группы</div>':''}${e?.trial?'<span class="badge amber">Ознакомительное</span>':''}${extra?'<label class="mini" style="display:block;margin-top:5px"><input type="checkbox" '+(e?.trial?'checked':'')+' onchange="toggleTrial('+c.id+',this.checked)"> Ознакомительное посещение</label>':''}</div><button class="photo ${photo?'done':''}" onclick="togglePhoto(${c.id})">${photo?'Фото ✓':'📷 Фото'}</button></div>`;
}
function startLesson(){let l=byId(state.lessons,state.selectedLesson);l.started=true;l.status='Идёт';render()}
function attend(id,v){byId(state.lessons,state.selectedLesson).attendance[id]=v;render()}
function togglePhoto(id){let l=byId(state.lessons,state.selectedLesson);l.photos[id]=!l.photos[id];render()}
function showExtraResults(q){
 const box=document.querySelector('#extraResults');if(!q){box.innerHTML='';return}let l=byId(state.lessons,state.selectedLesson),g=byId(state.groups,l.groupId);
 let res=state.children.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())&&!groupChildren(g.id).some(k=>k.id===c.id));
 box.innerHTML=res.slice(0,4).map(c=>`<button class="btn" style="width:100%;margin-top:6px;justify-content:flex-start" onclick="addExtra(${c.id})">${c.name}</button>`).join('');
}
function addExtra(id){let l=byId(state.lessons,state.selectedLesson),g=byId(state.groups,l.groupId),c=byId(state.children,id);if(!l.extras.some(e=>e.childId===id))l.extras.push({childId:id,trial:!c.enrollments.some(e=>e.direction===g.direction)});render()}
function finishLesson(){
 let l=byId(state.lessons,state.selectedLesson), presentIds=Object.entries(l.attendance).filter(([,v])=>v).map(([id])=>Number(id)).concat(l.extras.map(e=>e.childId)), missing=presentIds.filter(id=>!l.photos[id]).length;
 if(missing){modal(`<h3>Не у всех есть фотографии</h3><div class="notice">У ${missing} детей отсутствуют фотографии. Всё равно завершить занятие?</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Вернуться</button><button class="btn primary" onclick="confirmFinish()">Завершить всё равно</button></div>`)}else confirmFinish();
}
function confirmFinish(){let l=byId(state.lessons,state.selectedLesson),g=byId(state.groups,l.groupId);if(!l.attendanceApplied){Object.entries(l.attendance).filter(x=>x[1]).forEach(x=>{let c=byId(state.children,Number(x[0])),e=c&&c.enrollments.find(y=>y.direction===g.direction);if(e)e.balance-=1});l.extras.filter(x=>!x.trial).forEach(x=>{let c=byId(state.children,x.childId),e=c&&c.enrollments.find(y=>y.direction===g.direction);if(e)e.balance-=1});l.attendanceApplied=true}l.summary={present:Object.values(l.attendance).filter(Boolean).length+l.extras.length,trials:l.extras.filter(x=>x.trial).length,missing:Object.entries(l.attendance).filter(x=>x[1]&&!l.photos[x[0]]).length+l.extras.filter(x=>!l.photos[x.childId]).length};l.done=true;l.status='Проведено';state.modal=null;render()}
function payments(){
 return pageHead('Оплаты','Каждая оплата относится к одному ребёнку и одному направлению; цена фиксируется на момент операции','<button class="btn primary" onclick="paymentForm()">+ Оплата</button>')+`<div class="card list"><div class="row header"><div>Ребёнок</div><div>Направление</div><div>Сумма</div><div>Дата</div><div>Занятий</div></div>${state.payments.slice().reverse().map(p=>`<div class="row"><div><b>${byId(state.children,p.childId).name}</b><div class="muted mini">${p.method}</div></div><div>${p.direction}</div><div class="money">${money(p.amount)}</div><div>${p.date}</div><div><span class="badge green">+${Number(p.lessons).toFixed(p.lessons%1?2:0)}</span></div></div>`).join('')}</div>`;
}
function paymentForm(childId=1,direction='Робототехника'){
 modal(`<h3>Новая оплата</h3><div class="form-grid"><div class="field"><label>Дата</label><input class="input" id="pf-date" type="date" value="2026-09-09"></div><div class="field"><label>Ребёнок</label><select class="select" id="pf-child" onchange="updatePaymentPrice()">${state.children.map(c=>`<option value="${c.id}" ${c.id===childId?'selected':''}>${c.name}</option>`).join('')}</select></div><div class="field"><label>Направление</label><select class="select" id="pf-dir" onchange="updatePaymentPrice()"><option ${direction==='Робототехника'?'selected':''}>Робототехника</option><option ${direction==='Программирование'?'selected':''}>Программирование</option></select></div><div class="field"><label>Сумма, ₽</label><input class="input" id="pf-amount" type="number" step="0.01" value="4100" oninput="updatePaymentPrice()"></div><div class="field span-2"><label>Способ получения</label><select class="select" id="pf-method"><option>На счёт iCube</option><option>Наличными партнёру</option></select></div></div><div class="notice" id="pf-calc" style="margin-top:14px"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Отмена</button><button class="btn primary" onclick="savePayment()">Сохранить оплату</button></div>`);setTimeout(updatePaymentPrice,0);
}
function currentEnrollment(){let c=byId(state.children,Number(document.querySelector('#pf-child')?.value));return c?.enrollments.find(e=>e.direction===document.querySelector('#pf-dir')?.value)}
function updatePaymentPrice(){let e=currentEnrollment(),price=effectivePrice(e),sum=Number(document.querySelector('#pf-amount')?.value||0),box=document.querySelector('#pf-calc');if(box)box.innerHTML=`Цена на момент оплаты: <b>${money(price)}</b> · будет начислено <b>${(sum/price).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')} занятия</b>. Внутреннее значение не округляется.`}
function savePayment(){let childId=Number(document.querySelector('#pf-child').value),direction=document.querySelector('#pf-dir').value,e=byId(state.children,childId).enrollments.find(x=>x.direction===direction);if(!e){alert('Для теста выберите направление, на которое ребёнок уже записан.');return}let price=effectivePrice(e),amount=Number(document.querySelector('#pf-amount').value),lessons=amount/price;e.balance+=lessons;state.payments.push({id:Date.now(),date:document.querySelector('#pf-date').value.split('-').reverse().join('.'),childId,direction,amount,method:document.querySelector('#pf-method').value,price,lessons});state.modal=null;state.page='payments';render()}
function toggleTrial(id,v){let l=byId(state.lessons,state.selectedLesson),e=l.extras.find(x=>x.childId===id);if(e)e.trial=v;render()}\nfunction refunds(){return pageHead('Возвраты','Отдельный тип финансовой операции — не отрицательная оплата','<button class="btn primary" onclick="refundForm()">+ Возврат</button>')+`<div class="card list"><div class="row header"><div>Ребёнок</div><div>Направление</div><div>Сумма</div><div>Дата</div><div>Баланс</div></div>${state.refunds.map(r=>`<div class="row"><div><b>${byId(state.children,r.childId).name}</b></div><div>${r.direction}</div><div class="money negative">−${money(r.amount)}</div><div>${r.date}</div><div>−${r.lessons}</div></div>`).join('')}</div>`}
function refundForm(){modal('<h3>Новый возврат</h3><div class="form-grid"><div class="field"><label>Дата</label><input class="input" id="rf-date" type="date" value="2026-09-09"></div><div class="field"><label>Ребёнок</label><select class="select" id="rf-child" onchange="refreshRefundDirections()">'+state.children.map(c=>'<option value="'+c.id+'">'+c.name+'</option>').join('')+'</select></div><div class="field"><label>Направление</label><select class="select" id="rf-dir"></select></div><div class="field"><label>Сумма, ₽</label><input class="input" id="rf-amount" type="number" step="0.01" value="1025"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Отмена</button><button class="btn primary" onclick="saveRefund()">Сохранить</button></div>');setTimeout(refreshRefundDirections,0)}
function refreshRefundDirections(){let c=byId(state.children,Number(document.querySelector('#rf-child')?.value)),box=document.querySelector('#rf-dir');if(box)box.innerHTML=(c?.enrollments||[]).map(e=>'<option>'+e.direction+'</option>').join('')}
function saveRefund(){let childId=Number(document.querySelector('#rf-child').value),direction=document.querySelector('#rf-dir').value,c=byId(state.children,childId),e=c.enrollments.find(x=>x.direction===direction),amount=Number(document.querySelector('#rf-amount').value);if(!e||!amount)return;let price=effectivePrice(e),lessons=amount/price;e.balance-=lessons;state.refunds.push({id:Date.now(),date:document.querySelector('#rf-date').value.split('-').reverse().join('.'),childId,direction,amount,price,lessons});state.modal=null;state.page='refunds';render()}
function balances(){
 const entries=state.children.flatMap(c=>c.enrollments.map(e=>({c,e}))).sort((a,b)=>a.e.balance-b.e.balance);
 return pageHead('Балансы и долги','Баланс отдельно по каждому направлению. Отрицательный баланс не блокирует посещение.')+`<div class="grid cols-3" style="margin-bottom:16px"><div class="card metric"><div class="label">Долг</div><div class="value negative">${entries.filter(x=>x.e.balance<0).length}</div></div><div class="card metric"><div class="label">Ноль</div><div class="value">${entries.filter(x=>x.e.balance===0).length}</div></div><div class="card metric"><div class="label">Осталось 1</div><div class="value" style="color:var(--amber)">${entries.filter(x=>x.e.balance===1).length}</div></div></div><div class="card list"><div class="row header"><div>Ребёнок</div><div>Направление</div><div>Группа</div><div>Цена</div><div>Баланс</div></div>${entries.map(({c,e})=>`<div class="row clickable" onclick="openChild(${c.id})"><div><b>${c.name}</b></div><div>${e.direction}</div><div>${byId(state.groups,e.groupId).name}</div><div>${money(effectivePrice(e))}</div><div class="money ${e.balance<0?'negative':e.balance>0?'positive':''}">${Number(e.balance.toFixed(4))}</div></div>`).join('')}</div>`;
}
function salary(){
 const rows=[{date:'12.08',group:'Роботы · Чт 14:00',n:7,type:'normal'},{date:'19.08',group:'Роботы · Чт 14:00',n:5,type:'normal'},{date:'26.08',group:'Роботы · Чт 14:00',n:0,type:'empty'},{date:'02.09',group:'Роботы · Чт 14:00',n:6,type:'normal'}];
 let total=rows.reduce((s,r)=>s+(r.type==='empty'?state.settings.salaryEmpty:state.settings.salaryFix+r.n*state.settings.salaryChild),0);
 return pageHead('Зарплата','Табель по проведённым занятиям. Преподаватель этот раздел не видит.','<button class="btn">Скачать PDF</button>')+`<div class="toolbar"><select class="select" style="max-width:240px"><option>Иванов Сергей</option><option>Смирнова Алина</option></select><input class="input" type="date" value="2026-08-10" style="max-width:170px"><input class="input" type="date" value="2026-09-10" style="max-width:170px"><button class="btn primary">Применить</button></div><div class="card list"><div class="row header"><div>Дата / группа</div><div>Детей</div><div>Фикс</div><div>За детей</div><div>Итого</div></div>${rows.map(r=>{let fix=r.type==='empty'?state.settings.salaryEmpty:state.settings.salaryFix,child=r.type==='empty'?0:r.n*state.settings.salaryChild,total=fix+child;return `<div class="row"><div><b>${r.date}</b><div class="muted mini">${r.group}${r.type==='empty'?' · Пустой выезд':''}</div></div><div>${r.n}</div><div>${money(fix)}</div><div>${money(child)}</div><div class="money">${money(total)}</div></div>`}).join('')}</div><div class="card pad" style="margin-top:14px;display:flex;justify-content:space-between;font-size:18px"><b>Итого за период</b><b>${money(total)}</b></div>`;
}
function partner(){
 const pay=41000,tax=pay*state.settings.tax/100,salary=10000,dist=pay-tax-salary,icube=dist*state.settings.icubeShare/100,partner=dist*state.settings.partnerShare/100,cash=8000,transfer=partner-cash;
 return pageHead('Партнёрский расчёт','Проект «Зебра» · произвольный период')+`<div class="toolbar"><input class="input" type="date" value="2026-08-25" style="max-width:180px"><input class="input" type="date" value="2026-09-25" style="max-width:180px"><button class="btn primary">Рассчитать</button></div><div class="grid cols-2"><div class="card pad"><div class="section-title"><h2>Расчёт прибыли</h2></div><div class="partner-calc"><div class="calc-line"><span>Все оплаты</span><b>${money(pay)}</b></div><div class="calc-line"><span>Налог ${state.settings.tax}%</span><b class="negative">−${money(tax)}</b></div><div class="calc-line"><span>ЗП преподавателя</span><b class="negative">−${money(salary)}</b></div><div class="calc-line total"><span>К распределению</span><span>${money(dist)}</span></div><div class="calc-line"><span>iCube ${state.settings.icubeShare}%</span><b>${money(icube)}</b></div><div class="calc-line"><span>Екатерина ${state.settings.partnerShare}%</span><b>${money(partner)}</b></div></div></div><div class="card pad"><div class="section-title"><h2>Кто кому переводит</h2></div><div class="calc-line"><span>Доля Екатерины</span><b>${money(partner)}</b></div><div class="calc-line"><span>Уже у Екатерины наличными</span><b>${money(cash)}</b></div><div style="margin-top:18px;padding:18px;border-radius:12px;background:var(--greenbg)"><div class="muted">Перевести Екатерине</div><div style="font-size:30px;font-weight:800;color:var(--green)">${money(transfer)}</div></div><div class="muted mini" style="margin-top:10px">Если наличных у партнёра станет больше итоговой доли, блок автоматически должен показывать сумму к передаче iCube.</div></div></div>`;
}
function stats(){return pageHead('Статистика','Зарезервировано под будущую аналитику; в v1 без сложных отчётов')+`<div class="grid cols-3"><div class="card metric"><div class="label">Средняя посещаемость</div><div class="value">82%</div><div class="progress"><span style="width:82%"></span></div></div><div class="card metric"><div class="label">Занятий в сентябре</div><div class="value">14</div></div><div class="card metric"><div class="label">Средняя группа</div><div class="value">6,4</div></div></div><div class="card pad" style="margin-top:16px"><div class="empty">Здесь позже появятся динамика детей, выручка, долги, наполняемость и эффективность групп.</div></div>`}
function settings(){
 let s=state.settings;
 return pageHead('Настройки','Административные параметры. Исторические операции должны хранить снимок действовавших значений.')+`<div class="card"><div class="settings-block"><h3>Стоимость занятий</h3><div class="setting-row"><div><b>Робототехника</b><div class="muted mini">Базовая цена направления</div></div><input class="input" type="number" value="${s.robotPrice}" onchange="state.settings.robotPrice=Number(this.value)"></div><div class="setting-row"><div><b>Программирование</b><div class="muted mini">Базовая цена направления</div></div><input class="input" type="number" value="${s.codePrice}" onchange="state.settings.codePrice=Number(this.value)"></div></div><div class="settings-block"><h3>Зарплата</h3>${[['Фикс обычного занятия','salaryFix'],['За присутствующего ребёнка','salaryChild'],['Ознакомительное занятие','salaryIntro'],['Пустой выезд','salaryEmpty']].map(([l,k])=>`<div class="setting-row"><div><b>${l}</b></div><input class="input" type="number" value="${s[k]}" onchange="state.settings.${k}=Number(this.value)"></div>`).join('')}</div><div class="settings-block"><h3>Партнёрство</h3>${[['Налог, %','tax'],['Доля iCube, %','icubeShare'],['Доля партнёра, %','partnerShare']].map(([l,k])=>`<div class="setting-row"><div><b>${l}</b></div><input class="input" type="number" value="${s[k]}" onchange="state.settings.${k}=Number(this.value)"></div>`).join('')}<div class="notice" style="margin-top:14px">В production изменение настроек создаёт новую историческую версию и не пересчитывает закрытые операции.</div></div></div>`;
}
function render(){
 let content='',title='iCube CRM';
 if(state.role==='teacher'){if(!['teacherToday','teacherLesson'].includes(state.page))state.page='teacherToday';content=state.page==='teacherLesson'?teacherLesson():teacherToday();document.querySelector('#app').innerHTML=teacherShell(content)+(state.modal?`<div class="modal-backdrop"><div class="modal">${state.modal}</div></div>`:'');return}
 const pages={dashboard,children,child,groups,group,sites,teachers,calendar,lesson,payments,refunds,balances,salary,partner,stats,settings};content=(pages[state.page]||dashboard)();document.querySelector('#app').innerHTML=shell(content,title)+(state.modal?`<div class="modal-backdrop"><div class="modal">${state.modal}</div></div>`:'');
}
render();